name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Starting deployment..."
          
          # Navigate to project directory (update this path as needed)
          cd resonance-landing-api || { echo "Project directory not found"; exit 1; }
          
          # Pull latest code
          echo "Pulling latest code..."
          git pull origin main
          
          # Install/update dependencies
          echo "Installing dependencies..."
          npm install
          
          # Build the project
          echo "Building project..."
          npm run build
          docker-compose down
          docker-compose up -d --build --no-cache

          echo "Deployment completed successfully!" 